### ISSUE TITLE
Protein ligand docking using AMDock was unsuccessful

### ISSUE THREAD

**Issue by seal28** [Valdes-Tresanco-MS/AMDock#11]
Hi, 
   Today I tried to perform protein-ligand docking using the autodock-vina module of AMDock. I had prior knowledge about the ligand-binding site and hence I selected the "center on residues" option in the "define search space" section and went ahead with it. However, this step was not successful and I got an error. It was written as "ValueError: invalid literal for float(): -1.#QO". Being unaware of coding languages I don't understand what does it mean. I would request anyone who understands this issue to kindly help me to solve it.
Thank You
[sacyp_csa_dock_proj1.log](https://github.com/Valdes-Tresanco-MS/AMDock/files/6481193/sacyp_csa_dock_proj1.log)

**Comment by Valdes-Tresanco-MS** [comment]
Of course, we will help you. According to the record you attach, you have some problems with the PDB. In order to speed up the process, you can send the files (Protein and ligand) to my email (mariosergiovaldes145@gmail.com) to review them and the residues to select.
Best!
Mario S.
