### ISSUE TITLE
Problems running the shell script on ubuntu 20.04

### ISSUE THREAD

**Issue by ggoetten** [Valdes-Tresanco-MS/AMDock#13]
Unfortunately it is not possible to install pyqt4 without compiling it from scratch (it is no longer supported in the python repository or even in the official ubuntu, or debian repos) but I cant  compile it even after installing the sip required package. It is a shame that the windows version works so well. Cant you just give us a compiled software like the windows version has?

**Comment by Valdes-Tresanco-MS** [comment]
Hi @ggoetten 
Thanks for using AMDock.
I will try to create a docker container that is platform-independent so there will be no compatibility issues. It is a temporary solution. We are working on the AMDock2 version, which may take a while, but we will definitely release it.

Mario S

**Comment by ggoetten** [comment]
HI @Valdes-Tresanco-MS, thank you for your software. It is really great! 

Even an appimage might work if you can do it.

Thanks again

**Comment by Valdes-Tresanco-MS** [comment]
@ggoetten After a long time, I took time off of the holidays to try to improve my use of AMDock. Currently, it is a trial version since I have not been able to fully check all the functionalities. I hope you can use it and it will help you.
Sincerely
Mario S.
