### ISSUE TITLE
Using PyMOL installed with macport on macOS 10.13.6?

### ISSUE THREAD

**Issue by houdini69** [Valdes-Tresanco-MS/AMDock#19]
Hi,
Is it possible to use AMDock with PyMOL installed with macport on macOS 10.13.6? In this case pathway of PyMOL starting script is /opt/local/bin/pymol.
I've tried to compile pymol directly from source but it failed...
Laurent

**Comment by Valdes-Tresanco-MS** [comment]
I need to do the tests since I am not an expert in macOS. I remember that I spent a lot of work to get the pymol installation to work. I will test and let you know

**Comment by houdini69** [comment]
Thank you. On my side I think I am not far from being able to compile PyMOL from sources.

**Comment by houdini69** [comment]
Hi,
I finally succeeded to compile PyMOL with Conda package manager from PyMOL sources. However, I couldn't select Plugin-> Plugin Manager to install grid_amdock.py! I got an error window "No module named PyQt5.uic.

**Comment by Valdes-Tresanco-MS** [comment]
You must make sure that you have PyQt5 installed in such a control environment. 
```bash
python -m pip install pyqt5
```

**Comment by houdini69** [comment]
Tried to install AMDock and then compile pymol from the beginning in conda environnment. AMDock installation was ok. After installing dependencies (glew glm and netcdf4) compilation of pymol failed with at the end,

Traceback (most recent call last):
  File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.10/multiprocessing/pool.py", line 268, in __del__
  File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.10/multiprocessing/queues.py", line 377, in put
  File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.10/multiprocessing/connection.py", line 205, in send_bytes
  File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.10/multiprocessing/connection.py", line 405, in _send_bytes
AttributeError: 'NoneType' object has no attribute 'pack'

What does it mean?

**Comment by Valdes-Tresanco-MS** [comment]
I do not have much information regarding this. I have not yet tested python 3.10 in production, so I am currently oblivious to what bugs it may have. Please tell me the specifics so I can try to reproduce the bug. 
macOS Version.
PyMOL version and if it the open-source version

Please try using python 3.8 or 3.9 and see if you have the same problems. I will try to reproduce the problem as soon as possible.

**Comment by houdini69** [comment]
Ok. I finally succeeded to properly install AMDock. I just have to use AMDock tutorial!

**Comment by pillar-github** [comment]
how you solve the problem: ModuleNotFoundError: No module named 'pymol'. 

> macOS Version: 10.13.6 High Sierra PyMOL(TM) Molecular Graphics System, Version 2.6.0a0. Open Source version from https://github.com/schrodinger/pymol-open-source.
> 
> pymol compilation succeeded using python 3.9 with same error as previously. I can start pymol in AMDock env. However I couldn't start AMDock in AMDock env and I got AMDock Traceback (most recent call last): File "/Users/xxxx/miniconda3/envs/AMDock/bin/AMDock", line 5, in from AMDock.Docking_Program import run File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 9, in from AMDock.result_tab import Results File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/result_tab.py", line 9, in from AMDock.variables import Variables File "/Users/xxxx/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/variables.py", line 6, in import AutoDockTools, pymol ModuleNotFoundError: No module named 'pymol'

**Comment by houdini69** [comment]
I had to move all builded/compiled modules (glew, glm, netcdf4, pmw, libpng, freetype, libxml2) with conda in AMDock site-packages folder (/Users/xxxxxxx/miniconda3/envs/AMDock/lib/python3.9/site-packages/ folder
