### ISSUE TITLE
Unable to start AMDock

### ISSUE THREAD

**Issue by pjmartel** [Valdes-Tresanco-MS/AMDock#22]
I installed AMDock withing a conda environment, as instructed. When I try to launch AMDock, I get the followin errors:
```
Qt: Session management error: None of the authentication protocols specified are supported
Traceback (most recent call last):
  File "/home/martel/miniconda3/envs/AMDock/bin/AMDock", line 8, in <module>
    sys.exit(run())
  File "/home/martel/miniconda3/envs/AMDock/lib/python3.10/site-packages/AMDock/Docking_Program.py", line 160, in run
    splash = SplashScreen(QPixmap(v.splashscreen_path), app)
  File "/home/martel/miniconda3/envs/AMDock/lib/python3.10/site-packages/AMDock/splash_screen.py", line 37, in __init__
    progress_bar.setValue(ml)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

I am running Ubuntu 18.04  and Miniconda 4.8.2 with Python 3.10.6 . The PyMOL installation within the AMDock environment works
fine. 

I tried fixing the error by using the 'int' function on the argument of `setValue`, but then the  sa,e error crops up on the followinng functions:

```
self.nposes_value.setMinimum(1.0)
self.nposes_value.setMaximum(20.0)
self.nposes_value.setSingleStep(1.0)
```
when I replace those arguments with integers values the program loads to the main panel, but when I click
on any of the buttons to select a docking program, I get a crash with thte following errors:

```
Qt: Session management error: None of the authentication protocols specified are supported

Unhandled Python exception
Aborted (core dumped)
```

Thanks,
Paulo

**Comment by Valdes-Tresanco-MS** [comment]
Thank you Paulo for reporting the error. I reproduced the error, however, I don't have time to fix it at the moment. You can use AMDock by following these installation instructions.
```bash
conda create -n AMDock python=3.9
conda activate AMDock
conda install -c conda-forge pymol-open-source openbabel pdb2pqr
python -m pip install git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3 PyQt5 AMDock
```

**Comment by pjmartel** [comment]
Hello Mario,

thanks for the help. I had figured it out in the meantime that it was a python 3.10 problem, but on Ubuntu 18.04  (at least in my system), one cannot issue the following command:
```
conda create -n AMDock python=3.9
```
because it will complain later about a missing GLIBC libary version
I had to postpone the installation of python 3.9 to the next  command:
```
conda install -c conda-forge pymol-open-source openbabel pdb2pqr python=3.9
```
and now it works!
