### ISSUE TITLE
I have to talk on this repository soon.

### ISSUE THREAD

**Issue by RamsteinWR** [Valdes-Tresanco-MS/AMDock#8]
Will you reply here something. or contact me at +16268031601 or gerialworld@gmail.com

**Comment by Valdes-Tresanco-MS** [comment]
Yes, I will do it. Any problem, suggestion or doubt, I will attend it in the shortest possible time

**Comment by RamsteinWR** [comment]
Hey, 
1. I have to use this repository as a Python framework or module not using GUI,
2. converted into python3
3. and especially, our team is working on the COVID-19 hackathon with ml, and I have to use this framework to shortlist the ligands based on the binding energy and RMSD, and that sort of many kinds of stuff.
so from your side will you let me know all of the execution steps happening here?
call me on +16268031601 if possible.

**Comment by RamsteinWR** [comment]
It's not even getting installed on ubuntu and i have almost inspected completly this repository. So share here something important.
